### PR TITLE
FEAT: Compilation for rst docs inclusion

### PR DESCRIPTION
**Pull request by daquinteroflex**

### CODE REVIEW

**Comment by Lius-fe** [comment]
@daquinteroflex Can you explain the purpose of this PR? I think this repository is the only source of data for the FAQ. According to the description on the [ticket](https://flow360.atlassian.net/browse/MKTG-312), there should be no files other than those in .md format.
FYI: @ydflex

**Comment by daquinteroflex** [comment]
Hi Lius,

I've been testing the strategies to keep in sync this new repo that contains the tidy3d-faq and the main documentation from the main tidy3d repository. I am still to decide which is the best solution so if you have any feedback let me know.

My approach was to have this repo as a submodule within `tidy3d/docs` like this https://github.com/flexcompute/tidy3d/tree/dario/upgrade_faq_m2r3/docs . I first tried to include all the raw markdown files within the _faq directory but ran into a few issues. Our parser can deal with markdown, but not Jekyll within markdown, and also I can't include the metadata sections of the files because they're not pure markdown.

eg.

```
##### Everything between the ---- we can't accept or have to preprocess it out #####
---
_schema: default
title: How do I get the monitor data at a certain index?
date: 2023-12-19 14:49:03
enabled: true
category: Data Visualization and Postprocessing
_inputs:
  title:
    type: text
    label: QUESTION TITLE
  enabled:
    type: switch
    hidden: true
  date:
    type: datetime
    label: DATE
    instance_value: NOW
  category:
    type: select
    options:
      values: data.faq_categories
      value_key: key
      preview:
        text:
          - key: category_name
---
The simulation data is stored as a&nbsp;[DataArray](https://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)&nbsp;object using the&nbsp;[xarray](https://xarray.pydata.org/en/stable/)&nbsp;package. You can think of it as a dataset where data is stored as a large, multi-dimensional array (like a numpy array) and the coordinates along each of the dimensions are specified so it is easy to work with.

You can use the `isel()` method to select data at certain coordinates index. For example:

##### These div strings are Jekyll and not pure markdown which complicate things #####
<div><div markdown class="code-snippet">{% highlight python %}

# Run the simulation and get the data.
sim_data = tidy3d.web.run(simulation, task_name="task", path="data/data.hdf5", verbose=True)

# Get all the data from a field monitor.
field_data = sim_data["field"]

# Get field data for a specific frequency index.
field_freq_3 = field_data.isel(f=3)

{% endhighlight %}
{% include copy-button.html %}</div><p>You can find detailed information about simulation data visualization and postprocessing in this <a href="https://www.flexcompute.com/tidy3d/examples/notebooks/VizData/">tutorial</a>.</p></div>
```

So as a result of the Jekyll strings and the metadata I realised I needed to do some preprocessing of the raw files in `_faq` like in this PR. I've written a script that compiles all of this.

Does this script interfere with your stuff? I was thinking that it could be automated so that in any change in this repo it would preprocess and compile them, and then I can include the `index.rst` file directly in the documentation.

Let me know any feedback as there's a few ways to solve this!

**Comment by Lius-fe** [comment]
@daquinteroflex thanks for your clarification. As described in the ticket, We need to establish metadata standards for FAQs. such as which version of tidy3d does this answer pertain to? So it is necessary to include metadata in the markdown file.

Usually, metadata will contain the following. please refer to "_**Expected state > 1**_" in this [ticket](https://flow360.atlassian.net/browse/MKTG-312)
```
---
title: How are results normalized?
date: 2023-10-24 15:21:50
enabled: true
category: Sources
versions: 
 - 2.5.0
 - 2.4.0
---
```

Please be aware, never modify the content under the _faqs folder because other repositories also depend on this one. If the file format is changed, other repositories might encounter issues. 

I've reviewed your PR, I noticed you created a new folder(docs) as a submodule. it won't affect other repositories and it doesn't interfere with anything. Please go ahead.

Answer your questions: You can use a regular to match what's between two dashes in a file, and then use `yaml` module to load. 

eg.
```python
import re
import yaml # pip install PyYAML
import json

def extract_content_between_dashed(content):
    pattern = re.compile(r'---\n(.*?)\n---', re.DOTALL)
    match = pattern.search(content)
    if match:
        yml_content = yaml.safe_load(match.group(1).strip())
        # You can convert it to JSON format or other format if you needed
    else:
        return None
```
if you don't need this section please ignore or remove it.

Let me know if you have any questions.

**Comment by daquinteroflex** [comment]
Sounds like a plan. I'll finsh doing the modifications and include this metadata visualisation too. Thanks again Shuang

I'll request your final review before we merge

* TODO pending the github actions inclusion

**Comment by daquinteroflex** [comment]
I've reviewed this does not affect anything other than the `docs/` directory I created, and the trigger Github action. I think I need to rebase the commits into the main branch in order to test so will do that now.

**Pull request merged**
